module.exports = [
  {
    "id": 1,
    "title": "Web Design",
    "description": "Modern website design",
    "price": 5000,
    "category": "Design",
    "providerName": "Ali",
    "rating": 4.5,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 2,
    "title": "Logo Design",
    "description": "Creative logo design",
    "price": 2000,
    "category": "Design",
    "providerName": "Ahmed",
    "rating": 4.2,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 3,
    "title": "Math Tutor",
    "description": "Online math tutoring",
    "price": 1500,
    "category": "Education",
    "providerName": "Sara",
    "rating": 4.8,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 4,
    "title": "Plumbing Service",
    "description": "Fix pipes and leaks",
    "price": 3000,
    "category": "Home",
    "providerName": "Usman",
    "rating": 4.1,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 5,
    "title": "Graphic Design",
    "description": "Social media designs",
    "price": 2500,
    "category": "Design",
    "providerName": "Hina",
    "rating": 4.6,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 6,
    "title": "Mobile Repair",
    "description": "Fix smartphones",
    "price": 1800,
    "category": "Tech",
    "providerName": "Bilal",
    "rating": 4.3,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 7,
    "title": "Laptop Repair",
    "description": "Fix laptops and PCs",
    "price": 3500,
    "category": "Tech",
    "providerName": "Hamza",
    "rating": 4.4,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 8,
    "title": "English Tutor",
    "description": "Spoken English classes",
    "price": 1200,
    "category": "Education",
    "providerName": "Ayesha",
    "rating": 4.7,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 9,
    "title": "Physics Tutor",
    "description": "Online physics classes",
    "price": 1600,
    "category": "Education",
    "providerName": "Zain",
    "rating": 4.5,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 10,
    "title": "Car Repair",
    "description": "Engine and maintenance",
    "price": 6000,
    "category": "Auto",
    "providerName": "Rizwan",
    "rating": 4.2,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 11,
    "title": "AC Repair",
    "description": "Air conditioner service",
    "price": 4000,
    "category": "Home",
    "providerName": "Asad",
    "rating": 4.3,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 12,
    "title": "Electrician",
    "description": "Electrical fixing",
    "price": 2500,
    "category": "Home",
    "providerName": "Imran",
    "rating": 4.1,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 13,
    "title": "Painting Service",
    "description": "House painting",
    "price": 7000,
    "category": "Home",
    "providerName": "Noman",
    "rating": 4,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 14,
    "title": "Video Editing",
    "description": "Professional video editing",
    "price": 4500,
    "category": "Media",
    "providerName": "Faizan",
    "rating": 4.6,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 15,
    "title": "Photo Editing",
    "description": "Photo retouching",
    "price": 2000,
    "category": "Media",
    "providerName": "Saad",
    "rating": 4.4,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 16,
    "title": "Content Writing",
    "description": "SEO blog writing",
    "price": 1500,
    "category": "Writing",
    "providerName": "Maha",
    "rating": 4.7,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 17,
    "title": "Copywriting",
    "description": "Marketing copy",
    "price": 2200,
    "category": "Writing",
    "providerName": "Kiran",
    "rating": 4.5,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 18,
    "title": "SEO Expert",
    "description": "Website ranking",
    "price": 5000,
    "category": "Marketing",
    "providerName": "Tariq",
    "rating": 4.3,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 19,
    "title": "Social Media Manager",
    "description": "Manage accounts",
    "price": 3500,
    "category": "Marketing",
    "providerName": "Sana",
    "rating": 4.6,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 20,
    "title": "Digital Marketing",
    "description": "Ads campaigns",
    "price": 6000,
    "category": "Marketing",
    "providerName": "Umer",
    "rating": 4.4,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 21,
    "title": "Fitness Trainer",
    "description": "Personal training",
    "price": 3000,
    "category": "Health",
    "providerName": "Adnan",
    "rating": 4.7,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 22,
    "title": "Yoga Instructor",
    "description": "Online yoga classes",
    "price": 2000,
    "category": "Health",
    "providerName": "Nida",
    "rating": 4.5,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 23,
    "title": "Diet Plan",
    "description": "Custom diet plans",
    "price": 1800,
    "category": "Health",
    "providerName": "Hira",
    "rating": 4.6,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 24,
    "title": "Makeup Artist",
    "description": "Bridal makeup",
    "price": 8000,
    "category": "Beauty",
    "providerName": "Iqra",
    "rating": 4.8,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 25,
    "title": "Hair Stylist",
    "description": "Hair cutting & styling",
    "price": 2500,
    "category": "Beauty",
    "providerName": "Rabia",
    "rating": 4.4,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 26,
    "title": "Tailor Service",
    "description": "Clothes stitching",
    "price": 3000,
    "category": "Fashion",
    "providerName": "Shahid",
    "rating": 4.2,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 27,
    "title": "Fashion Designer",
    "description": "Custom outfits",
    "price": 9000,
    "category": "Fashion",
    "providerName": "Mehwish",
    "rating": 4.7,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 28,
    "title": "Interior Designer",
    "description": "Home interior design",
    "price": 10000,
    "category": "Home",
    "providerName": "Farah",
    "rating": 4.6,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 29,
    "title": "Gardening",
    "description": "Garden maintenance",
    "price": 2000,
    "category": "Home",
    "providerName": "Yasir",
    "rating": 4.1,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 30,
    "title": "Cleaning Service",
    "description": "House cleaning",
    "price": 2500,
    "category": "Home",
    "providerName": "Akram",
    "rating": 4.3,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 31,
    "title": "Delivery Service",
    "description": "Fast delivery",
    "price": 800,
    "category": "Logistics",
    "providerName": "Salman",
    "rating": 4,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 32,
    "title": "Courier Service",
    "description": "Parcel delivery",
    "price": 1000,
    "category": "Logistics",
    "providerName": "Danish",
    "rating": 4.2,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 33,
    "title": "Driving Instructor",
    "description": "Learn driving",
    "price": 3000,
    "category": "Education",
    "providerName": "Junaid",
    "rating": 4.5,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 34,
    "title": "Music Teacher",
    "description": "Guitar lessons",
    "price": 2000,
    "category": "Education",
    "providerName": "Arham",
    "rating": 4.6,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 35,
    "title": "Cooking Classes",
    "description": "Learn cooking",
    "price": 1800,
    "category": "Education",
    "providerName": "Bushra",
    "rating": 4.7,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 36,
    "title": "Event Planner",
    "description": "Event management",
    "price": 15000,
    "category": "Events",
    "providerName": "Zoya",
    "rating": 4.8,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 37,
    "title": "Photographer",
    "description": "Event photography",
    "price": 7000,
    "category": "Media",
    "providerName": "Sameer",
    "rating": 4.5,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 38,
    "title": "Videographer",
    "description": "Video shoots",
    "price": 8000,
    "category": "Media",
    "providerName": "Owais",
    "rating": 4.6,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 39,
    "title": "Translator",
    "description": "Language translation",
    "price": 1200,
    "category": "Writing",
    "providerName": "Adeel",
    "rating": 4.4,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 40,
    "title": "Data Entry",
    "description": "Typing work",
    "price": 1000,
    "category": "IT",
    "providerName": "Naveed",
    "rating": 4.2,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 41,
    "title": "Web Developer",
    "description": "Full stack dev",
    "price": 10000,
    "category": "IT",
    "providerName": "Talha",
    "rating": 4.7,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 42,
    "title": "App Developer",
    "description": "Mobile apps",
    "price": 12000,
    "category": "IT",
    "providerName": "Rehan",
    "rating": 4.6,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 43,
    "title": "Game Developer",
    "description": "Game development",
    "price": 15000,
    "category": "IT",
    "providerName": "Huzaifa",
    "rating": 4.5,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 44,
    "title": "Cyber Security",
    "description": "Security audit",
    "price": 11000,
    "category": "IT",
    "providerName": "Fahad",
    "rating": 4.4,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 45,
    "title": "Cloud Engineer",
    "description": "Cloud setup",
    "price": 13000,
    "category": "IT",
    "providerName": "Waqas",
    "rating": 4.3,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 46,
    "title": "Voice Over",
    "description": "Professional voice",
    "price": 2500,
    "category": "Media",
    "providerName": "Shayan",
    "rating": 4.6,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 47,
    "title": "Animation",
    "description": "2D animations",
    "price": 5000,
    "category": "Media",
    "providerName": "Ammar",
    "rating": 4.5,
    "location": "Lahore",
    "availability": true
  },
  {
    "id": 48,
    "title": "Resume Writing",
    "description": "Professional CV",
    "price": 1500,
    "category": "Writing",
    "providerName": "Fatima",
    "rating": 4.7,
    "location": "Islamabad",
    "availability": true
  },
  {
    "id": 49,
    "title": "Interview Prep",
    "description": "Mock interviews",
    "price": 2000,
    "category": "Education",
    "providerName": "Kashif",
    "rating": 4.6,
    "location": "Karachi",
    "availability": true
  },
  {
    "id": 50,
    "title": "Virtual Assistant",
    "description": "Admin support",
    "price": 1800,
    "category": "Business",
    "providerName": "Laiba",
    "rating": 4.5,
    "location": "Lahore",
    "availability": true
  }
];
